#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Joern Ihlenburg
"""Generate tests/data/unstructured_rgg.mtx (SPD, unstructured sparsity).

Construction: n points uniform in the unit square (fixed seed), edges
between pairs closer than RADIUS with random positive weights in
[0.5, 1.5); A = L + SHIFT*I where L is the weighted graph Laplacian.
L is PSD by construction, so lambda_min(A) >= SHIFT — tests rely on this
documented bound for rigorous solution-difference checks.

Pure-stdlib and deterministic: rerunning this script reproduces the
committed fixture byte-for-byte.
"""

import random

N = 400
RADIUS = 0.11
SHIFT = 0.1
SEED = 20260711

rng = random.Random(SEED)
pts = [(rng.random(), rng.random()) for _ in range(N)]

adj = {}  # (i, j) i<j -> weight
for i in range(N):
    for j in range(i + 1, N):
        dx = pts[i][0] - pts[j][0]
        dy = pts[i][1] - pts[j][1]
        if dx * dx + dy * dy < RADIUS * RADIUS:
            adj[(i, j)] = 0.5 + rng.random()

deg = [0.0] * N
for (i, j), w in adj.items():
    deg[i] += w
    deg[j] += w

# Lower triangle of A = L + SHIFT*I in MatrixMarket symmetric coordinate
# format: diagonal deg[i] + SHIFT, off-diagonal -w.
entries = [(i, i, deg[i] + SHIFT) for i in range(N)]
entries += [(j, i, -w) for (i, j), w in adj.items()]  # j > i: lower triangle
entries.sort()

lines = [
    "%%MatrixMarket matrix coordinate real symmetric",
    f"% SPD fixture: random geometric graph Laplacian + {SHIFT}*I",
    f"% Generated by scripts/make_unstructured_fixture.py (seed {SEED});",
    "% lambda_min >= 0.1 by construction (documented, used by tests).",
    f"{N} {N} {len(entries)}",
]
lines += [f"{r + 1} {c + 1} {v!r}" for r, c, v in entries]

with open("tests/data/unstructured_rgg.mtx", "w", encoding="ascii") as f:
    f.write("\n".join(lines) + "\n")

print(f"wrote tests/data/unstructured_rgg.mtx: n={N}, entries={len(entries)}")
